services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - USE_SQLITE=False
      - MYSQL_DATABASE=onlineshop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=onlineshop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: