# Generated by Django 5.0.14 on 2025-05-03 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='techlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='techlist',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.techlist'),
        ),
        migrations.AddField(
            model_name='techlist',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techlist',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AddField(
            model_name='techlist',
            name='image_url',
            field=models.URLField(blank=True, db_column='ImageURL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='techlist',
            name='on_sale',
            field=models.BooleanField(db_column='OnSale', default=False),
        ),
        migrations.AddField(
            model_name='techlist',
            name='on_wishlist',
            field=models.BooleanField(db_column='OnWishlist', default=False),
        ),
        migrations.AddField(
            model_name='techlist',
            name='product_name',
            field=models.CharField(db_column='ProductName', default='Unnamed Product', max_length=255),
        ),
        migrations.AddField(
            model_name='techlist',
            name='stars',
            field=models.DecimalField(db_column='Rating', decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='techlist',
            name='stock_quantity',
            field=models.IntegerField(db_column='StockQuantity', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(db_column='Token', default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='techlist',
            name='brand',
            field=models.CharField(blank=True, db_column='Brand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techlist',
            name='category',
            field=models.CharField(blank=True, db_column='Category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techlist',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.techlist')),
            ],
        ),
    ]
