# Generated by Django 5.0.14 on 2025-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_tech_remove_techlist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlist',
            name='stock_quantity',
            field=models.IntegerField(db_column='StockQuantity', default=0),
        ),
    ]
