# Generated by Django 5.0.14 on 2025-05-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250504_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlist',
            name='stars',
            field=models.DecimalField(db_column='Rating', decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
