# Generated by Django 5.0.14 on 2025-05-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_techlist_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techlist',
            name='stars',
        ),
    ]
